[package]
name = "k8s-rs-pb"
version = "0.1.0"
authors = ["Dmitriy Mastitskiy <dimulgator@outlook.com>"]
edition = "2021"
license = "MIT"
publish = true

[dependencies]
protobuf = "3.7.1"
serde = {version="1.0.215", features = ["derive"]}
serde_json = "1.0.133"
chrono = "0.4.38"
k8s-openapi = { version = "0.23.0", features = ["latest"] }